-- Create voice_notes table
CREATE TABLE IF NOT EXISTS voice_notes (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    ticket_id UUID NOT NULL REFERENCES tickets(id) ON DELETE CASCADE,
    filename VARCHAR(255) NOT NULL,
    original_name VARCHAR(255) NOT NULL,
    file_size BIGINT NOT NULL,
    duration_seconds DECIMAL(10,2),
    mime_type VARCHAR(100) DEFAULT 'audio/wav',
    file_path TEXT NOT NULL,
    upload_status VARCHAR(20) DEFAULT 'pending' CHECK (upload_status IN ('pending', 'uploaded', 'failed')),
    user_identifier VARCHAR(255),
    metadata JSONB DEFAULT '{}',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create indexes for better performance
CREATE INDEX IF NOT EXISTS idx_voice_notes_ticket_id ON voice_notes(ticket_id);
CREATE INDEX IF NOT EXISTS idx_voice_notes_user_identifier ON voice_notes(user_identifier);
CREATE INDEX IF NOT EXISTS idx_voice_notes_created_at ON voice_notes(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_voice_notes_upload_status ON voice_notes(upload_status);
CREATE INDEX IF NOT EXISTS idx_voice_notes_duration ON voice_notes(duration_seconds);

-- Create updated_at trigger (reuse the function from attachments table)
CREATE TRIGGER update_voice_notes_updated_at
    BEFORE UPDATE ON voice_notes
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- Enable RLS (Row Level Security)
ALTER TABLE voice_notes ENABLE ROW LEVEL SECURITY;

-- Create RLS policies for voice_notes
-- Allow all operations since we removed auth
CREATE POLICY "Allow all operations on voice_notes" ON voice_notes
    FOR ALL USING (true);

-- Add comments for documentation
COMMENT ON TABLE voice_notes IS 'Stores voice note recordings associated with tickets';
COMMENT ON COLUMN voice_notes.id IS 'Unique identifier for the voice note';
COMMENT ON COLUMN voice_notes.ticket_id IS 'Foreign key reference to tickets table';
COMMENT ON COLUMN voice_notes.filename IS 'Generated filename for storage (UUID-based)';
COMMENT ON COLUMN voice_notes.original_name IS 'Original filename as generated by the system';
COMMENT ON COLUMN voice_notes.file_size IS 'File size in bytes';
COMMENT ON COLUMN voice_notes.duration_seconds IS 'Duration of the voice note in seconds';
COMMENT ON COLUMN voice_notes.mime_type IS 'MIME type of the audio file';
COMMENT ON COLUMN voice_notes.file_path IS 'Full path to the stored audio file';
COMMENT ON COLUMN voice_notes.upload_status IS 'Status of the file upload process';
COMMENT ON COLUMN voice_notes.user_identifier IS 'Identifier of the user who created the voice note';
COMMENT ON COLUMN voice_notes.metadata IS 'Additional metadata about the voice note (e.g., recording quality, device info)';